/*
 * Quiz App model specification
 * Quiz App model specification
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package hu.zol1e.quizapp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import hu.zol1e.quizapp.model.Answer;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PlayerAnswer
 */
@JsonPropertyOrder({
  PlayerAnswer.JSON_PROPERTY_PLAYER_ID,
  PlayerAnswer.JSON_PROPERTY_GAME_ID,
  PlayerAnswer.JSON_PROPERTY_QUESTION_ID,
  PlayerAnswer.JSON_PROPERTY_ANSWER
})
@JsonTypeName("PlayerAnswer")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-02-05T16:56:31.910437100+01:00[Europe/Prague]")
public class PlayerAnswer {
  public static final String JSON_PROPERTY_PLAYER_ID = "playerId";
  private String playerId;

  public static final String JSON_PROPERTY_GAME_ID = "gameId";
  private String gameId;

  public static final String JSON_PROPERTY_QUESTION_ID = "questionId";
  private String questionId;

  public static final String JSON_PROPERTY_ANSWER = "answer";
  private Answer answer;

  public PlayerAnswer() { 
  }

  public PlayerAnswer playerId(String playerId) {
    
    this.playerId = playerId;
    return this;
  }

   /**
   * Get playerId
   * @return playerId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_PLAYER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPlayerId() {
    return playerId;
  }


  @JsonProperty(JSON_PROPERTY_PLAYER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlayerId(String playerId) {
    this.playerId = playerId;
  }


  public PlayerAnswer gameId(String gameId) {
    
    this.gameId = gameId;
    return this;
  }

   /**
   * Get gameId
   * @return gameId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_GAME_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getGameId() {
    return gameId;
  }


  @JsonProperty(JSON_PROPERTY_GAME_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGameId(String gameId) {
    this.gameId = gameId;
  }


  public PlayerAnswer questionId(String questionId) {
    
    this.questionId = questionId;
    return this;
  }

   /**
   * Get questionId
   * @return questionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_QUESTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQuestionId() {
    return questionId;
  }


  @JsonProperty(JSON_PROPERTY_QUESTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuestionId(String questionId) {
    this.questionId = questionId;
  }


  public PlayerAnswer answer(Answer answer) {
    
    this.answer = answer;
    return this;
  }

   /**
   * Get answer
   * @return answer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ANSWER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Answer getAnswer() {
    return answer;
  }


  @JsonProperty(JSON_PROPERTY_ANSWER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAnswer(Answer answer) {
    this.answer = answer;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlayerAnswer playerAnswer = (PlayerAnswer) o;
    return Objects.equals(this.playerId, playerAnswer.playerId) &&
        Objects.equals(this.gameId, playerAnswer.gameId) &&
        Objects.equals(this.questionId, playerAnswer.questionId) &&
        Objects.equals(this.answer, playerAnswer.answer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(playerId, gameId, questionId, answer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlayerAnswer {\n");
    sb.append("    playerId: ").append(toIndentedString(playerId)).append("\n");
    sb.append("    gameId: ").append(toIndentedString(gameId)).append("\n");
    sb.append("    questionId: ").append(toIndentedString(questionId)).append("\n");
    sb.append("    answer: ").append(toIndentedString(answer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

