/*
 * Quiz App model specification
 * Quiz App model specification
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package hu.zol1e.quizapp.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import hu.zol1e.quizapp.model.Question;
import hu.zol1e.quizapp.model.Quiz;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * QuizGame
 */
@JsonPropertyOrder({
  QuizGame.JSON_PROPERTY_ID,
  QuizGame.JSON_PROPERTY_NAME,
  QuizGame.JSON_PROPERTY_STATE,
  QuizGame.JSON_PROPERTY_QUIZ,
  QuizGame.JSON_PROPERTY_ACTUAL_QUESTION,
  QuizGame.JSON_PROPERTY_QUESTION_START_TIME,
  QuizGame.JSON_PROPERTY_QUESTION_FINISH_TIME
})
@JsonTypeName("QuizGame")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-02-05T16:56:31.910437100+01:00[Europe/Prague]")
public class QuizGame {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  /**
   * Gets or Sets state
   */
  public enum StateEnum {
    CREATED("CREATED"),
    
    WAITING("WAITING"),
    
    QUESTION("QUESTION"),
    
    FINISHED("FINISHED");

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StateEnum fromValue(String value) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATE = "state";
  private StateEnum state;

  public static final String JSON_PROPERTY_QUIZ = "quiz";
  private Quiz quiz;

  public static final String JSON_PROPERTY_ACTUAL_QUESTION = "actualQuestion";
  private Question actualQuestion;

  public static final String JSON_PROPERTY_QUESTION_START_TIME = "questionStartTime";
  private OffsetDateTime questionStartTime;

  public static final String JSON_PROPERTY_QUESTION_FINISH_TIME = "questionFinishTime";
  private OffsetDateTime questionFinishTime;

  public QuizGame() { 
  }

  public QuizGame id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(String id) {
    this.id = id;
  }


  public QuizGame name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public QuizGame state(StateEnum state) {
    
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StateEnum getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(StateEnum state) {
    this.state = state;
  }


  public QuizGame quiz(Quiz quiz) {
    
    this.quiz = quiz;
    return this;
  }

   /**
   * Get quiz
   * @return quiz
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_QUIZ)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Quiz getQuiz() {
    return quiz;
  }


  @JsonProperty(JSON_PROPERTY_QUIZ)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuiz(Quiz quiz) {
    this.quiz = quiz;
  }


  public QuizGame actualQuestion(Question actualQuestion) {
    
    this.actualQuestion = actualQuestion;
    return this;
  }

   /**
   * Get actualQuestion
   * @return actualQuestion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ACTUAL_QUESTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Question getActualQuestion() {
    return actualQuestion;
  }


  @JsonProperty(JSON_PROPERTY_ACTUAL_QUESTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActualQuestion(Question actualQuestion) {
    this.actualQuestion = actualQuestion;
  }


  public QuizGame questionStartTime(OffsetDateTime questionStartTime) {
    
    this.questionStartTime = questionStartTime;
    return this;
  }

   /**
   * Get questionStartTime
   * @return questionStartTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_QUESTION_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getQuestionStartTime() {
    return questionStartTime;
  }


  @JsonProperty(JSON_PROPERTY_QUESTION_START_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuestionStartTime(OffsetDateTime questionStartTime) {
    this.questionStartTime = questionStartTime;
  }


  public QuizGame questionFinishTime(OffsetDateTime questionFinishTime) {
    
    this.questionFinishTime = questionFinishTime;
    return this;
  }

   /**
   * Get questionFinishTime
   * @return questionFinishTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_QUESTION_FINISH_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getQuestionFinishTime() {
    return questionFinishTime;
  }


  @JsonProperty(JSON_PROPERTY_QUESTION_FINISH_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQuestionFinishTime(OffsetDateTime questionFinishTime) {
    this.questionFinishTime = questionFinishTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QuizGame quizGame = (QuizGame) o;
    return Objects.equals(this.id, quizGame.id) &&
        Objects.equals(this.name, quizGame.name) &&
        Objects.equals(this.state, quizGame.state) &&
        Objects.equals(this.quiz, quizGame.quiz) &&
        Objects.equals(this.actualQuestion, quizGame.actualQuestion) &&
        Objects.equals(this.questionStartTime, quizGame.questionStartTime) &&
        Objects.equals(this.questionFinishTime, quizGame.questionFinishTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, state, quiz, actualQuestion, questionStartTime, questionFinishTime);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QuizGame {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    quiz: ").append(toIndentedString(quiz)).append("\n");
    sb.append("    actualQuestion: ").append(toIndentedString(actualQuestion)).append("\n");
    sb.append("    questionStartTime: ").append(toIndentedString(questionStartTime)).append("\n");
    sb.append("    questionFinishTime: ").append(toIndentedString(questionFinishTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

